---
version: 3

images:
  base_image:
    name: 'registry.redhat.io/ansible-automation-platform-25/ee-minimal-rhel9:latest'

options:
  package_manager_path: /usr/bin/microdnf

dependencies:
  system:
    - ansible-core
    - python3-pip
    - python3-devel
    - git-core
    - gcc-c++
    - cmake
    - make
    - openssl-devel
    - krb5-devel

  ansible_core:
    package_pip: ansible-core==2.14.18

  galaxy:
    collections:
      - ansible.windows
      - azure.azcollection
      - microsoft.ad

  python:
    - requests-credssp
